language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "./run_tests.sh"
before_install: 
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.2.deb
  - "./install_pyav_deps.sh"
services:
  - elasticsearch
